services:
  web:
    build: .
    environment:
      - ConnectionStrings:Notifications=Server=db;Database=notifications;User Id=SA;Password=SuperSecretPwd123%;TrustServerCertificate=true
    ports:
      - "5000:8080"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    volumes:
      - dbVolume:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SuperSecretPwd123%"
volumes:
  dbVolume:
