version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=password
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    