version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - app_network
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge